### ISSUE TITLE
People's Committee Needed For Administrative Purposes

### ISSUE THREAD

**Issue by JasonLeeH** [SocialistRA/socialistra.github.io#3]
Issues I see arising in the near-term:

- The various social media channels may hold substantive political disagreements (definition of "socialism", for example), which may lead to alienation of new members.
- With an entirely decentralized organization, it will be nearly impossible for the SRA as a complete body to launch coordinated campaigns.
- We'll need a treasurer in order to accept donations. I personally think the approach used by 'crowdmatch.me' is the best approach as it allows for concise monetary goals and democratic direction. I've also already got the Huey P. Newton Gunclub and Redneck Revolt on board with it. If this is decided upon, I'd gladly change the format of the site to better suit SRA goals.
- There are only two of us having dialogue about the future direction of the SRA here. This is not yet a group effort. We should bring the various Facebook group admins on as committee members and have continued conversation with those running the social media accounts.

**Comment by edmundjarvis** [comment]
Yeah, the left is absolutely full of political disagreements. Hopefully we can come up with some definition here that encompasses most groups in both the authoritarian and libertarian left.

**Comment by JasonLeeH** [comment]
Marked as closed due to the DSA, the largest socialist organization in the US, distancing itself from the Socialist International and solidifying support for Marxist-Leninist principles held by the Workers' World Party as well as the PSL.
